version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'actions/dependency-review-action'
        versions:
          # https://github.com/actions/dependency-review-action/issues/493
          - '3.0.5'
      - dependency-name: 'crate-ci/typos'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '@types/*'
        update-types: ['version-update:semver-major']
    groups:
      octokit-dependencies:
        patterns:
          - '@octokit/*'
      tsconfig-dependencies:
        patterns:
          - '@tsconfig/*'
      actions-dependencies:
        patterns:
          - '@actions/*'
