name: Linters
on:
  push:
    branches: [main]
    paths-ignore:
      - 'dist/**'
      - 'package-lock.json'
  pull_request:
    paths-ignore:
      - 'dist/**'
      - 'package-lock.json'
jobs:
  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: dprint/check@2f1cf31537886c3bfb05591c031f7744e48ba8a1 # v2.2
        with:
          dprint-version: '0.40.2' # selfup { "regex": "\\d[^']+", "script": "dprint --version | cut -d ' ' -f 2" }

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: crate-ci/typos@1ccb2ff8ad0982a2afcc3f4f473819df0d2e819f # v1.16.15 # selfup { "regex": "crate-ci/typos@\\S+ # \\S+", "script": "./scripts/get-typos-action-ref.bash" }
        with:
          files: |
            .
            .github
            .vscode
            .devcontainer
