name: Update nixpkgs and CI dependencies
on:
  pull_request:
    paths:
      - '.github/workflows/update-nixpkgs-and-versions-in-ci.yml'
  schedule:
    # Every Monday 10:17 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '17 1 * * 1'
  workflow_dispatch:

jobs:
  update-nixpkgs:
    uses: kachick/anylang-template/.github/workflows/reusable-update-nixpkgs-and-versions-in-ci.yml@e975e064e5e0acc3d99808ac9142bfba3c78a3b0
    if: (github.event.sender.login == 'kachick') || (github.event_name != 'pull_request')
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
      optional-run: |
        nix develop --command nix run github:kachick/selfup/v0.0.2 -- run --prefix='# selfup ' --skip-by='nix run' .github/ISSUE_TEMPLATE/*.yml
        git diff-index --quiet HEAD || git commit -m 'Update latest versions in issue template' .github
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
